### ISSUE TITLE
What about using a boostrap package?

### ISSUE THREAD

**Issue by mccrodp** [mathieul/brunch-with-elm-bootstrap#4]
Have you thought about using a boostrap package? What are your thoughts on that?

E.g. [`JeremyBellows/elm-bootstrapify`](http://package.elm-lang.org/packages/JeremyBellows/elm-bootstrapify/latest)

**Comment by mathieul** [comment]
Actually I started using [elm-bootstrap](http://elm-bootstrap.info/getting-started) yesterday for a side project and I'm loving it so far. The API is already really clean for a 1.0. (handles bootstrap v4, `elm-bootstrapify` is for v3).

I'm planning on updating the example with it when I have some time, maybe this week-end.

**Comment by mccrodp** [comment]
Even better, thanks for that @mathieul. I couldn't find a boostrap package for 0.18, if this works, perfect!

Looking forward to its inclusion. If you need help testing, ping me!

**Comment by mccrodp** [comment]
Hey @mathieul. I can try to make a start on this, this week if you haven't gotten around to it yet.

**Comment by mathieul** [comment]
Hey @mccrodp. I've given it a shot here: https://github.com/mathieul/brunch-with-elm-bootstrap/tree/elm-bootstrap - planning on merging to master a bit later.

**Comment by mccrodp** [comment]
That looks great so far @mathieul. I will give it a full look later on. How about creating a PR so that I can comment?

On first look, it looks like the api posts json have been duplicated on commit, the public dir needs to be added to `.gitignore` perhaps.

The README was missed on my PR, it still shows the older / more basic `Main.elm`, it might be good to persist this somewhere though, or is it obvious enough how to strip back the now slightly more involved program to a basic one like that?

Also, I forgot to add a comment or attribute the now Post.elm and Route.elm to the Bogdanp/elm-route repo. They came from that 0.18 repo version of https://github.com/elm-community/elm-route/tree/master/examples/app

This looks great though and I'm excited about using it on a personal project now that it has most of the pieces I need. Changing the posts.json linking to the dependency repos was a great idea too 👍  Thanks for this!

**Comment by mathieul** [comment]
Good catch, seems like I checked in the public file by mistake when I updated the `.gitignore`, and it didn't remove it when I reverted changes.

I'm not sure I understand what you mean regarding `README.md`. What changes do you think it needs? I've added a section about the code example, and you can comment on the PR I've just created: https://github.com/mathieul/brunch-with-elm-bootstrap/pull/5

Cheers.

**Comment by mccrodp** [comment]
>I'm not sure I understand what you mean regarding README.md. What changes do you think it needs? 

Nothing now that you added the code sample, I think that you are describing what's there and the Do it Yourself suggestion tells what to do to remove that. Looks good. Anything else I find now I'll add on the PR, just about to test manually.
